### ISSUE TITLE
JSON decode error when using custom nominatim domain

### ISSUE THREAD

**Issue by vovchykbratyk** [geopy/geopy#392]
When using a code to scrape a string input for places and then run that against a custom (internal to my org) nominatim service, I receive the following error:

```
Traceback (most recent call last):
  File "C:\anaconda3\envs\gpos\lib\site-packages\geopy\geocoders\base.py", line 404, in _call_geocoder
    return deserializer(page)
  File "C:\anaconda3\envs\gpos\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\anaconda3\envs\gpos\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\anaconda3\envs\gpos\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\PycharmProjects\geoparser\geoparser.py", line 22, in <module>
    location = geolocator.geocode(city)
  File "C:\anaconda3\envs\gpos\lib\site-packages\geopy\geocoders\osm.py", line 406, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\anaconda3\envs\gpos\lib\site-packages\geopy\geocoders\base.py", line 407, in _call_geocoder
    "Could not deserialize using deserializer:\n%s" % page
geopy.exc.GeocoderParseError: Could not deserialize using deserializer:

(and then the page css is printed for the rest of the error msg)
```

The code that works fine is:
```
geolocator = Nominatim(timeout=2, user_agent="Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0")
```

The code that throws the error is:
```
geolocator = Nominatim(domain="nominatim.local/nominatim", schema="http", timeout=2, user_agent="Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0")
```

The service is not behind a proxy and direct queries through the web interface execute without issue.  The full url is structured as http://nominatim.local/nominatim/search.php

**Comment by vovchykbratyk** [comment]
Oh, I started getting good results when I switched the domain to http://nominatim.local/nominatim/search.php, including the search.php on the end.  Sorry!  Closing the issue, maybe helpful if others run into something similar in the future though.
