### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'latitude' ? 

### ISSUE THREAD

**Issue by duarteleonardosales** [geopy/geopy#402]
The code gives me the latitude and longitude as desired, but right after that an error happens:
-4.5713706,-45.1322724
-4.5622825,-45.1328668
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\leonardo\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__ return self.func(*args)
  File "C:/Users/leonardo/Desktop/python program/evaluation/AUXILIO_leo_v9.py", line 159, in gps
    GPS_lat = location.latitude
AttributeError: 'NoneType' object has no attribute 'latitude'

A part of the code:
```
geolocator=Nominatim(user_agent="EData", timeout=10000)
 location_list=[]
       for i in range(0,n):
                location=geolocator.geocode(data_gps2[i])
                GPS_lat = location.latitude
                GPS_long = location.longitude
                location_list.append(f'{GPS_lat},{GPS_long}')
                print(location_list[i])
```
Outside of my program, I can use something like that but without 'loop' and without that error.
Any problem with tkinter ?? Any problem with loop (for) ??

**Comment by duarteleonardosales** [comment]
solved.
I think it was an address that needed more details, but I'm not sure, since I was also able to generate results with the less complete address. I put a ''time.sleep(5)'' at the end of the loop.
