### ISSUE TITLE
geopy  urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Rahulvks** [geopy/geopy#404]
Hi I am getting the below error kindly help me to fix this 

Error
```
RateLimiter caught an error, retrying (0/2 tries). Called with (*('nan,nan',), **{}).
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Code 
```
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
locator = Nominatim(user_agent="myGeocoder", timeout=10)
rgeocode = RateLimiter(locator.reverse, min_delay_seconds=0.001)
data_clean_1['address'] = data_clean_1['geom'].apply(rgeocode)
```

**Comment by KostyaEsmukov** [comment]
> `Called with (*('nan,nan',), **{})`

Looks like you were trying to resolve `nan` as coordinates instead of actual numbers, which of course would result in an error.

Next time please use StackOverflow for questions: https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#reporting-issues
