### ISSUE TITLE
geopy has stopped working at all

### ISSUE THREAD

**Issue by berndhahnebach** [geopy/geopy#458]
A few days ago geopy stopped working. I am not able to retrieve coordinates for any address ...

Attached some code. Does anyone has an idea what could cause this?

cheers bernd

```
from geopy.geocoders import Nominatim
gc = Nominatim(user_agent="cadgenerator")
gc.geocode("175 5th Avenue NYC")

```

```
Python 3.6.8 (v3.6.8:3c6b436a57, Mar 26 2019, 15:45:44) [MSC v.1916 64 bit (AMD64)] on win32
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> 
>>> 
>>> from geopy.geocoders import Nominatim
>>> gc = Nominatim(user_agent="cadgenerator")
>>> gc.geocode("175 5th Avenue NYC")
Traceback (most recent call last):
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\site-packages\geopy\geocoders\base.py", line 360, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\site-packages\geopy\adapters.py", line 373, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\site-packages\geopy\adapters.py", line 404, in _request
    text=resp.text,
geopy.adapters.AdapterHTTPError: Non-successful status code 403

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\site-packages\geopy\geocoders\nominatim.py", line 294, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\site-packages\geopy\geocoders\base.py", line 378, in _call_geocoder
    self._adapter_error_handler(error)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\site-packages\geopy\geocoders\base.py", line 392, in _adapter_error_handler
    raise exc_cls(str(error)) from error
geopy.exc.GeocoderInsufficientPrivileges: Non-successful status code 403
>>> 
```

**Comment by KostyaEsmukov** [comment]
1. geopy is a library, it cannot "stop working". See https://geopy.readthedocs.io/en/stable/#geopy-is-not-a-service
2. The issue tracker is not for usage questions. See https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#reporting-issues
3. Your specific error is probably caused by a too common user agent, or by generating too much requests to Nominatim. See the "Attention" block at https://geopy.readthedocs.io/en/stable/#geopy.geocoders.Nominatim and https://geopy.readthedocs.io/en/stable/#usage-with-pandas

**Comment by berndhahnebach** [comment]
thanks for your answers ... 

>     3\. by generating too much requests to Nominatim

I did just one request, only one address?  See my first post. This has been working before. There must be some more general problem with geopy and Nominatim or the code I used to access Nominatim.
