### ISSUE TITLE
Installation error (SyntaxError)

### ISSUE THREAD

**Issue by chehov** [geopy/geopy#75]
Caise syntaxError while install pachage by pip

```
pip install -U geopy
Downloading/unpacking geopy from https://pypi.python.org/packages/source/g/geopy/geopy-1.1.5.tar.gz#md5=c0ca5e67f2a839563e8268c8b1713d0c
  Downloading geopy-1.1.5.tar.gz (64kB): 64kB downloaded
  Running setup.py egg_info for package geopy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/chehov/.virtualenvs/.../build/geopy/setup.py", line 6, in <module>
        from geopy import __version__ as version
      File "geopy/__init__.py", line 9, in <module>
        from geopy.point import Point
      File "geopy/point.py", line 9, in <module>
        from geopy.format import (
      File "geopy/format.py", line 119
        for n, d
          ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/chehov/.virtualenvs/.../build/geopy/setup.py", line 6, in <module>

    from geopy import __version__ as version

  File "geopy/__init__.py", line 9, in <module>

    from geopy.point import Point

  File "geopy/point.py", line 9, in <module>

    from geopy.format import (

  File "geopy/format.py", line 119

    for n, d

      ^

SyntaxError: invalid syntax

----------------------------------------
```

https://github.com/geopy/geopy/blob/master/geopy/format.py#L119

P.S. Ubuntu 10.04, Python 2.6.5

**Comment by mbazyar** [comment]
But, we already have python 2.6 and it works like a man.
